import { appBarHeight } from "~/utils";
import type { AppsData } from "~/types";

const apps: AppsData[] = [
  {
    id: "launchpad",
    title: "Launchpad",
    desktop: false,
    img: "img/icons/launchpad.png",
  },
  {
    id: "bear",
    title: "Bear",
    desktop: true,
    width: 860,
    height: 500,
    show: true,
    y: -40,
    img: "img/icons/bear.png",
    content: <Bear />,
  },
  {
    id: "finder",
    title: "Profile",
    desktop: true,
    width: 600,
    height: 400,
    show: false,
    img: "img/ui/avatar.jpg", // Personalized icon for the Profile app
    content: <Finder />,
  },
  {
    id: "safari",
    title: "Safari",
    desktop: true,
    width: 1024,
    minWidth: 375,
    minHeight: 200,
    x: -20,
    img: "img/icons/safari.png",
    content: <Safari />,
  },
  {
    id: "facetime",
    title: "FaceTime",
    desktop: true,
    img: "img/icons/facetime.png",
    width: 500 * 1.7,
    height: 500 + appBarHeight,
    minWidth: 350 * 1.7,
    minHeight: 350 + appBarHeight,
    aspectRatio: 1.7,
    x: -80,
    y: 20,
    content: <FaceTime />,
  },
  {
    id: "terminal",
    title: "Terminal",
    desktop: true,
    img: "img/icons/terminal.png",
    content: <Terminal />,
  },
  {
    id: "github",
    title: "Github",
    desktop: false,
    img: "img/icons/github.png",
    link: "https://github.com/Mrhamza01",
  },
  {
    id: "spotify",
    title: "Spotify",
    desktop: true,
    width: 860,
    height: 500,
    show: false,
    y: -40,
    img: "img/icons/spotify.png",
    content: <Spotify />,
  },
  {
    id: "chat",
    title: "AI Chat",
    desktop: true,
    width: 400,
    height: 550,
    show: false,
    img: "img/icons/chatbot.png", // Custom AI Chatbot icon
    content: <Chat />,
  },
  {
    id: "siri",
    title: "Siri",
    desktop: true,
    width: 860,
    height: 500,
    show: false,
    y: -40,
    img: "img/icons/siri.png",
    content: <Siri />,
  },
  {
    id: "weather",
    title: "Weather",
    desktop: true,
    width: 400,
    height: 480,
    show: false,
    img: "img/icons/siri.png",
    content: <Weather />,
  },
  {
    id: "calculator",
    title: "Calculator",
    desktop: true,
    width: 280,
    height: 420,
    show: false,
    img: "img/icons/terminal.png",
    content: <Calculator />,
  },
  {
    id: "notes",
    title: "Notes",
    desktop: true,
    width: 400,
    height: 500,
    show: false,
    img: "img/icons/bear.png",
    content: <Notes />,
  },
  {
    id: "stocks",
    title: "Stocks",
    desktop: true,
    width: 380,
    height: 400,
    show: false,
    img: "img/icons/safari.png",
    content: <Stocks />,
  },
  {
    id: "architecture",
    title: "Architecture",
    desktop: true,
    width: 900,
    height: 560,
    show: false,
    y: -20,
    img: "img/icons/terminal.png",
    content: <Architecture />,
  },
  {
    id: "certificates",
    title: "Certificates",
    desktop: true,
    width: 480,
    height: 400,
    show: false,
    img: "img/icons/bear.png",
    content: <Certificates />,
  },
];

export default apps;
